### ISSUE TITLE
about Compressed sparse installation

### ISSUE THREAD

**Issue by BIT-glimmer** [coin-or/ADOL-C#21]
Hello. I have encountered this red warning when I configure during the installation.

Compressed sparse structures will not be available
Only sparsity patterns can be computed.
![2020-03-27 14-18-57屏幕截图](https://user-images.githubusercontent.com/46468777/77728031-8fb88180-7036-11ea-9511-74c16f2cd39f.png)

I think I have correctly installed the ColPack Library in the default path. I dont know why this happens.
It seems that i will not be able to use the sparse AD.
Please forrgive me if this question is naive. I'm quite new to this.
Thanks a lot. Best wishes.

**Comment by awalther1** [comment]
Hi,

I just checked the combination of ADOL-C an ColPack. The difficult point is that the ColPack version in the master branch has a different structure that the release 1.0.10. I will contact the ColPack developer to discuss this issue. In the meantime you could use the following to work with the compressed derivative matices:

Download ColPack version 1.0.10 from 

https://github.com/CSCsw/ColPack/releases

then install ColPack, e.g. in 

/home/mydir/AD/ColPack-1.0.10

such that there are the include and the lib directories there

Then configure ADOL-C using e.g. 

 ./configure --prefix=/home/mydir/AD/ADOL-C/adolc_base_2.7.2 --enable-addexa --enable-sparse  --with-colpack=/home/mydir/AD/ColPack-1.0.10

This should work. Otherwise just comment once more

Best  

Andrea

**Comment by BIT-glimmer** [comment]
Thanks a lot. Thar really helps and the ColPack part works now. But I came into a new problem now. I also need open_mp for doing some parallel computation in my research (multibody dynamics simulation). And when i try to configure it with this command, it's ok.
./configure --with-openmp-flag="-fopenmp" --enable-docexa --enable-addexa --enable-parexa --enable-sparse --with-colpack=/home/shuai/Shuai/codes/ColPack --enable-debug
But after that when i  type make, I got this new problem
![image](https://user-images.githubusercontent.com/46468777/77838854-41c48a80-71aa-11ea-9a0f-be2f8ded5fe1.png)
It suggests that i should modify the comment style in  /adolc/lie/drivers.h. But it's source file so I got confused.
Thanks for your time and patience.
Best wishes,
Shuai

**Comment by BIT-glimmer** [comment]
Hello,  prof. Walther
By the way, I just found the problem seems coming with that I turned on the "--enable-debug" on.  But I still don't know how to solve it. Thanks for your patience and time. 
Best wishes,
Shuai

**Comment by awalther1** [comment]
Hi Shuai,

I just commited a fix for the comments in C++ style. Could you try it again, please?

Best regards

Andrea

**Comment by BIT-glimmer** [comment]
Hello prof. Walther,

Thank you so much. It works now. 
Thanks for your time and patience. You are so kind.

Best wishes,
Shuai

**Comment by awalther1** [comment]
Hi Shuai,

great, thanks for the feedback!

Best regards

Andrea
